name: test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/test.yaml"
      - "requirements.txt"
  workflow_dispatch:

defaults:
  run:
    working-directory: "./src"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    env:
      INVOKE_IS_CI_CD: 1
      SYSTEM_VERSION_COMPAT: "0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade setuptools
      - name: Debug Python and pip info
        run: |
          python --version
          pip --version
          pip debug
      - name: Install invocation prerequisites
        run: |
          python -m pip install --verbose -Ur ../requirements.txt
        env:
          SETUPTOOLS_USE_DISTUTILS: ${{ runner.os == 'Windows' && 'stdlib' || null }}
          PIP_NO_BINARY: ":all:"  # Force source installations for macOS compatibility
          SYSTEM_VERSION_COMPAT: "0"  # Already set globally but reinforcing here
          ARCHFLAGS: "-arch x86_64"  # Help with compilation on macOS
          MACOSX_DEPLOYMENT_TARGET: "10.14"  # Set minimum macOS version
      - name: Get python version
        id: full-python-version
        shell: bash
        run: |
          echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")" >> $GITHUB_OUTPUT


